name: Formatter Workflow

on:
  workflow_call:
    inputs:
      BRANCH_FOLDER:
        required: true
        type: string

jobs:
  format:
    name: Prettify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: ${{ inputs.BRANCH_FOLDER }}
      - run: npm run format
        working-directory: ${{ inputs.BRANCH_FOLDER }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          push: "--force"
