name: Formatter Workflow

on:
  workflow_call:
    inputs:
      BRANCH_FOLDER:
        required: true
        type: string

jobs:
  format:
    name: Prettify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prettify Code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write /home/runner/work/PRONTO/PRONTO/${{ inputs.BRANCH_FOLDER }}/**/*.{js,ts,css,html,json,svelte} --ignore-path /home/runner/work/PRONTO/PRONTO/${{ inputs.BRANCH_FOLDER }}/.prettierignore
          prettier_plugins: "prettier-plugin-svelte prettier-plugin-tailwindcss"
          only_changed: true
          same_commit: true
