name: Webclient Development Workflow

on:
  push:
    branches:
      - webclient/development

jobs:
  webclient-format-flow:
    uses: ./.github/workflows/webclient.formatter.yml
    with:
      BRANCH_FOLDER: webclient

  webclient-test-flow:
    strategy:
      matrix:
        testtype: [e2e, unit]
        testsuite: [default]
    uses: ./.github/workflows/webclient.tester.yml
    with:
      BRANCH_FOLDER: webclient
      TEST_TYPE: ${{ matrix.testtype }}
      TEST_SUITE: ${{ matrix.testsuite }}

  webclient-lint-flow:
    needs: [webclient-format-flow, webclient-test-flow]
    uses: ./.github/workflows/webclient.linter.yml
    secrets: inherit
    with:
      BRANCH_FOLDER: webclient
      COMMIT_SHA: ${{ needs.webclient-format-flow.outputs.COMMIT_SHA }}